### PR TITLE
option to download image from url added to pipette image elements

### PR DESCRIPTION
**Pull request by chr1sgrant**
depends on PR #238 in antha-lang/antha

### CODE REVIEW

**Comment by gogogadgetbioprocess** [comment]
This has ballooned slightly to include refactored Pipette image from palette and MakePalette protocols

**Comment by chr1sgrant** [comment]
@synthacebot test this please

**Comment by chr1sgrant** [comment]
@synthacebot test this please

**Comment by chr1sgrant** [comment]
@synthacebot test this please

**Comment by chr1sgrant** [comment]
@synthacebot test this please

**Pull request merged**
